name: Create Release

on:
  push:
    branches: [ "main" ]  # This is the branch where the tag is pushed
  create:  # This needs to specify a rule for tags, perhaps using tags: [ "v*"`]
    name: "Create release on tag"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"

        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: path/to/eml_to_msg.exe
          asset_name: eml_to_msg.exe
          asset_content_type: application/octet-stream

        env:
          GITHUB_REF: ${{ github.ref }}
