name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Dies ist das automatische Token von GitHub
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automatisch generiertes Release für ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Wieder das Token verwenden
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: path/to/eml_to_msg.exe
          asset_name: eml_to_msg.exe
          asset_content_type: application/octet-stream
