name: Create Release

on:
  push:
    branches: [ "main" ] # This defines that the workflow triggers when changes are pushed to branch "main"
  create:
    name: Create release on tag # This creates a rule that triggers when a new tag is pushed, e.g., v1.0.0
    tags: [ "v*" ] # This specifies which tags will trigger the rule (e.g., any tag starting with "v")

jobs:
  create-release-and-upload:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          body: "Automatisch generiertes Release für ${{ github.ref }}"

        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: path/to/eml_to_msg.exe
          asset_name: eml_to_msg.exe
          asset_content_type: application/octet-stream

        env:
          GITHUB_REF: ${{ github.ref }}
